INSERT INTO venues (venue_name, location) VALUES
                                              ('Grand Hall Phnom Penh', 'Phnom Penh'),
                                              ('Siem Reap Convention Center', 'Siem Reap'),
                                              ('Battambang Event Space', 'Battambang'),
                                              ('Royal Garden Venue', 'Phnom Penh'),
                                              ('Mekong Riverside Hall', 'Kratie'),
                                              ('Angkor Ballroom', 'Siem Reap'),
                                              ('Diamond Island Center', 'Phnom Penh'),
                                              ('Lotus Conference Hall', 'Takeo'),
                                              ('Sunrise Event Plaza', 'Kampot'),
                                              ('Golden Crown Hall', 'Phnom Penh'),
                                              ('Ocean View Venue', 'Sihanoukville'),
                                              ('Harmony Hall', 'Kandal'),
                                              ('Victory Conference Center', 'Kampong Cham'),
                                              ('Elite Grand Ballroom', 'Phnom Penh'),
                                              ('Palm Garden Venue', 'Prey Veng'),
                                              ('Skyline Rooftop Hall', 'Phnom Penh'),
                                              ('Heritage Event Space', 'Siem Reap'),
                                              ('Emerald Banquet Hall', 'Kampong Speu'),
                                              ('Blue River Conference Hall', 'Pursat'),
                                              ('Orchid Luxury Venue', 'Phnom Penh');

INSERT INTO attendees (attendee_name, email) VALUES
                                                 ('John Doe', 'john.doe@example.com'),
                                                 ('Jane Smith', 'jane.smith@example.com'),
                                                 ('Michael Brown', 'michael.brown@example.com'),
                                                 ('Emily Davis', 'emily.davis@example.com'),
                                                 ('Daniel Wilson', 'daniel.wilson@example.com'),
                                                 ('Sophia Martinez', 'sophia.martinez@example.com'),
                                                 ('James Anderson', 'james.anderson@example.com'),
                                                 ('Olivia Taylor', 'olivia.taylor@example.com'),
                                                 ('William Thomas', 'william.thomas@example.com'),
                                                 ('Ava Jackson', 'ava.jackson@example.com'),
                                                 ('Benjamin White', 'benjamin.white@example.com'),
                                                 ('Isabella Harris', 'isabella.harris@example.com'),
                                                 ('Lucas Martin', 'lucas.martin@example.com'),
                                                 ('Mia Thompson', 'mia.thompson@example.com'),
                                                 ('Henry Garcia', 'henry.garcia@example.com'),
                                                 ('Charlotte Martinez', 'charlotte.martinez@example.com'),
                                                 ('Alexander Robinson', 'alexander.robinson@example.com'),
                                                 ('Amelia Clark', 'amelia.clark@example.com'),
                                                 ('Ethan Rodriguez', 'ethan.rodriguez@example.com'),
                                                 ('Harper Lewis', 'harper.lewis@example.com');

INSERT INTO events (event_name, even_date, venue_id) VALUES
                                                          ('Tech Conference 2026', '2026-04-01', 1),
                                                          ('Music Festival', '2026-04-02', 2),
                                                          ('Startup Meetup', '2026-04-03', 3),
                                                          ('AI Workshop', '2026-04-04', 4),
                                                          ('Business Seminar', '2026-04-05', 5),
                                                          ('Art Exhibition', '2026-04-06', 6),
                                                          ('Gaming Tournament', '2026-04-07', 7),
                                                          ('Health Conference', '2026-04-08', 8),
                                                          ('Food Expo', '2026-04-09', 9),
                                                          ('Education Fair', '2026-04-10', 10),
                                                          ('Developer Summit', '2026-04-11', 1),
                                                          ('Marketing Workshop', '2026-04-12', 2),
                                                          ('Photography Event', '2026-04-13', 3),
                                                          ('Design Conference', '2026-04-14', 4),
                                                          ('Blockchain Meetup', '2026-04-15', 5),
                                                          ('Finance Seminar', '2026-04-16', 6),
                                                          ('Fitness Bootcamp', '2026-04-17', 7),
                                                          ('Movie Screening', '2026-04-18', 8),
                                                          ('Networking Night', '2026-04-19', 9),
                                                          ('Science Fair', '2026-04-20', 10);

INSERT INTO events (event_name, even_date, venue_id) VALUES
                                                          ('Tech Conference 2026', '2026-04-01', 1),
                                                          ('Music Festival', '2026-04-02', 2),
                                                          ('Startup Meetup', '2026-04-03', 3),
                                                          ('AI Workshop', '2026-04-04', 4),
                                                          ('Business Seminar', '2026-04-05', 5),
                                                          ('Art Exhibition', '2026-04-06', 6),
                                                          ('Gaming Tournament', '2026-04-07', 7),
                                                          ('Health Conference', '2026-04-08', 8),
                                                          ('Food Expo', '2026-04-09', 9),
                                                          ('Education Fair', '2026-04-10', 10),
                                                          ('Developer Summit', '2026-04-11', 1),
                                                          ('Marketing Workshop', '2026-04-12', 2),
                                                          ('Photography Event', '2026-04-13', 3),
                                                          ('Design Conference', '2026-04-14', 4),
                                                          ('Blockchain Meetup', '2026-04-15', 5),
                                                          ('Finance Seminar', '2026-04-16', 6),
                                                          ('Fitness Bootcamp', '2026-04-17', 7),
                                                          ('Movie Screening', '2026-04-18', 8),
                                                          ('Networking Night', '2026-04-19', 9),
                                                          ('Science Fair', '2026-04-20', 10);

INSERT INTO event_attendee (attendee_id, event_id) VALUES
                                                       (1,1),
                                                       (2,1),
                                                       (3,2),
                                                       (4,2),
                                                       (5,3),
                                                       (6,3),
                                                       (7,4),
                                                       (8,4),
                                                       (9,5),
                                                       (10,5),
                                                       (11,6),
                                                       (12,6),
                                                       (13,7),
                                                       (14,7),
                                                       (15,8),
                                                       (16,8),
                                                       (17,9),
                                                       (18,9),
                                                       (19,10),
                                                       (16,10);